name: multi_bootstrap

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- flutter analyze --no-fatal-infos
    description: Run flutter analyze in all packages

  test:
    run: melos exec -- flutter test --coverage
    description: Run tests in all packages
    packageFilters:
      dirExists: test

  test:unit:
    run: melos exec -- flutter test --coverage
    description: Run unit tests only
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- dart format .
    description: Format all packages

  format:check:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Check formatting in all packages

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  build:web:
    run: |
      cd apps/mobile && flutter build web --release --dart-define-from-file=.env.prod
    description: Build web release

  build:android:
    run: |
      cd apps/mobile && flutter build apk --release --flavor prod --dart-define-from-file=.env.prod
    description: Build Android release APK

  build:ios:
    run: |
      cd apps/mobile && flutter build ios --release --flavor prod --dart-define-from-file=.env.prod --no-codesign
    description: Build iOS release (no codesign)

  run:dev:
    run: |
      cd apps/mobile && flutter run --flavor dev --dart-define-from-file=.env.dev
    description: Run app with dev flavor

  run:stage:
    run: |
      cd apps/mobile && flutter run --flavor stage --dart-define-from-file=.env.stage
    description: Run app with stage flavor

  run:prod:
    run: |
      cd apps/mobile && flutter run --flavor prod --dart-define-from-file=.env.prod
    description: Run app with prod flavor

  run:web:
    run: |
      cd apps/mobile && flutter run -d chrome --dart-define-from-file=.env.dev
    description: Run app on web (dev)

  generate:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner in all packages
    packageFilters:
      dependsOn: build_runner
